"""Configurando6

Revision ID: 2f26f2aca5e9
Revises: 983844df6877
Create Date: 2025-05-20 01:31:04.202019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f26f2aca5e9'
down_revision: Union[str, None] = '983844df6877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comanda', 'id_client',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comanda', 'id_client',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
