"""Configurando5

Revision ID: 983844df6877
Revises: ba02b29b1623
Create Date: 2025-05-19 14:04:39.403407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983844df6877'
down_revision: Union[str, None] = 'ba02b29b1623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido_item', 'observacao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido_item', 'observacao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
