"""Configurando4

Revision ID: ba02b29b1623
Revises: 9d399909478f
Create Date: 2025-05-19 14:01:37.671900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba02b29b1623'
down_revision: Union[str, None] = '9d399909478f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido_item', 'id_produto',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedido_item', 'id_combo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido_item', 'id_combo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pedido_item', 'id_produto',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
