"""Configurando7

Revision ID: ce978df764e7
Revises: 2f26f2aca5e9
Create Date: 2025-05-21 11:38:42.482126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce978df764e7'
down_revision: Union[str, None] = '2f26f2aca5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cliente', ['email'])
    op.create_unique_constraint(None, 'cliente', ['documento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente', type_='unique')
    op.drop_constraint(None, 'cliente', type_='unique')
    # ### end Alembic commands ###
